"""Emit a Fusion 360 script folder that rebuilds a plan's default state as
named bodies grouped in components, with the plan's numeric DEFAULTS synced
to User Parameters so a rerun after an edit rebuilds.

Folder layout (install under %APPDATA%\\Autodesk\\Autodesk Fusion 360\\API\\Scripts\\):
    <Name>/<Name>.py         the runner below
    <Name>/<Name>.manifest
    <Name>/plan.py           copy of the plan module
    <Name>/shopcad/          geometry.py and __init__.py so plan.py imports work
"""

import json
import os
import shutil

RUNNER = r'''"""__NAME__ - Fusion 360 script generated by shopcad.

Run from Utilities > Add-Ins > Scripts and Add-Ins (Shift+S) in an empty
design. Dimensions come from User Parameters (created on the first run from
the drawing-set numbers); edit them under Modify > Change Parameters and run
again to rebuild.
"""
import adsk.core
import adsk.fusion
import traceback
import os
import sys
import math
import importlib

IN = 2.54  # Fusion internal unit is cm


def _p(x, y, z):
    return adsk.core.Point3D.create(x * IN, y * IN, z * IN)


def _rot(px, py, deg, x, y):
    a = math.radians(deg)
    dx, dy = x - px, y - py
    return px + dx * math.cos(a) - dy * math.sin(a), py + dx * math.sin(a) + dy * math.cos(a)


def _box(tb, s):
    x, y, z = s["origin"]
    w, d, h = s["size"]
    cx, cy, cz = x + w / 2.0, y + d / 2.0, z + h / 2.0
    ldx, ldy = 1.0, 0.0
    wdx, wdy = 0.0, 1.0
    if s.get("rz"):
        px, py = s["pivot"]
        cx, cy = _rot(px, py, s["rz"], cx, cy)
        a = math.radians(s["rz"])
        ldx, ldy = math.cos(a), math.sin(a)
        wdx, wdy = -math.sin(a), math.cos(a)
    obb = adsk.core.OrientedBoundingBox3D.create(
        _p(cx, cy, cz),
        adsk.core.Vector3D.create(ldx, ldy, 0),
        adsk.core.Vector3D.create(wdx, wdy, 0),
        w * IN, d * IN, h * IN)
    return tb.createBox(obb)


def _cyl(tb, s):
    x, y, z = s["base"]
    dx, dy, dz = {"x": (1, 0, 0), "y": (0, 1, 0), "z": (0, 0, 1)}[s["axis"]]
    L = s["length"]
    x2, y2, z2 = x + dx * L, y + dy * L, z + dz * L
    if s.get("rz"):
        px, py = s["pivot"]
        x, y = _rot(px, py, s["rz"], x, y)
        x2, y2 = _rot(px, py, s["rz"], x2, y2)
    return tb.createCylinderOrCone(_p(x, y, z), s["r"] * IN, _p(x2, y2, z2), s["r"] * IN)


def _shape(tb, s):
    return _box(tb, s) if s["shape"] == "box" else _cyl(tb, s)


def _sync(design, defaults):
    ups = design.userParameters
    values = {}
    for name, val in defaults.items():
        if not isinstance(val, (int, float)) or isinstance(val, bool):
            values[name] = val
            continue
        unitless = isinstance(val, int)
        param = ups.itemByName(name)
        if param is None:
            if unitless:
                param = ups.add(name, adsk.core.ValueInput.createByReal(float(val)), "", "__NAME__: count")
            else:
                param = ups.add(name, adsk.core.ValueInput.createByString("%g in" % val), "in", "__NAME__: inches")
        values[name] = int(round(param.value)) if unitless else param.value / IN
    return values


def run(context):
    ui = None
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        design = adsk.fusion.Design.cast(app.activeProduct)
        if not design:
            ui.messageBox("Open a Fusion design first, then run __NAME__.")
            return
        here = os.path.dirname(os.path.abspath(__file__))
        if here not in sys.path:
            sys.path.insert(0, here)
        import plan
        importlib.reload(plan)
        P = _sync(design, plan.DEFAULTS)
        scene = plan.build(P, plan.STATES[plan.DEFAULT_STATE])
        root = design.rootComponent
        tb = adsk.fusion.TemporaryBRepManager.get()
        for occ in list(root.occurrences):
            if occ.component.description == "__NAME__":
                occ.deleteMe()
        parametric = design.designType == adsk.fusion.DesignTypes.ParametricDesignType
        count = 0
        for comp_name, parts in scene.components().items():
            occ = root.occurrences.addNewComponent(adsk.core.Matrix3D.create())
            comp = occ.component
            comp.name = comp_name
            comp.description = "__NAME__"
            base = None
            if parametric:
                base = comp.features.baseFeatures.add()
                base.startEdit()
            try:
                for s in parts:
                    body = _shape(tb, s["shape"])
                    for c in s.get("cuts", []):
                        tb.booleanOperation(body, _shape(tb, c), adsk.fusion.BooleanTypes.DifferenceBooleanType)
                    added = comp.bodies.add(body, base) if parametric else comp.bodies.add(body)
                    added.name = s["name"]
                    count += 1
            finally:
                if base is not None:
                    base.finishEdit()
        app.activeViewport.fit()
        ui.messageBox("__NAME__ built %d bodies in %d components." % (count, len(scene.order)))
    except Exception:
        if ui:
            ui.messageBox("__NAME__ failed:\n{}".format(traceback.format_exc()))
'''


def emit(mod, plan_file, out_dir, shopcad_dir):
    name = getattr(mod, "FUSION_NAME", "".join(w.capitalize() for w in mod.NAME.split()))
    folder = os.path.join(out_dir, name)
    if os.path.isdir(folder):
        shutil.rmtree(folder)
    os.makedirs(os.path.join(folder, "shopcad"))
    with open(os.path.join(folder, name + ".py"), "w", encoding="utf-8") as f:
        f.write(RUNNER.replace("__NAME__", name))
    with open(os.path.join(folder, name + ".manifest"), "w", encoding="utf-8") as f:
        json.dump({"autodeskProduct": "Fusion360", "type": "script", "author": "shopcad",
                   "description": {"": "Builds the %s from its drawing set as parametric components." % mod.NAME},
                   "supportedOS": "windows|mac", "editEnabled": True}, f, indent=4)
    shutil.copy(plan_file, os.path.join(folder, "plan.py"))
    shutil.copy(os.path.join(shopcad_dir, "geometry.py"), os.path.join(folder, "shopcad", "geometry.py"))
    with open(os.path.join(folder, "shopcad", "__init__.py"), "w") as f:
        f.write("")
    zip_base = os.path.join(out_dir, name.lower() + "-fusion-script")
    return shutil.make_archive(zip_base, "zip", out_dir, name)
