time-format %H:%M:%S
date-format %Y-%m-%d
log-format {"ClientAddr":"%^","ClientHost":"%h","ClientPort":"%^","ClientUsername":"%^","DownstreamContentSize":%b,"DownstreamStatus":%s,"Duration":%^,"OriginContentSize":%^,"OriginDuration":%^,"OriginStatus":%^,"Overhead":%^,"RequestAddr":"%^","RequestContentSize":%^,"RequestCount":%^,"RequestHost":"%v","RequestMethod":"%m","RequestPath":"%U","RequestPort":"%^","RequestProtocol":"%H","RequestScheme":"%^","RetryAttempts":%^,"RouterName":"%^","ServiceAddr":"%^","ServiceName":"%^","ServiceURL":"%^","StartLocal":"%^","StartUTC":"%dT%t.%^"}
geoip-database /geoip/dbip-country.mmdb
real-time-html true
ws-url wss://logs.rt-541.io:443/ws
port 7890
output /report/index.html
html-report-title GoAccess - logs.rt-541.io
