---
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:proton-v2.3.2
    container_name: enshrouded
    restart: unless-stopped
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    deploy:
      resources:
        limits:
          cpus: '6.00'
          memory: 10G
        reservations:
          cpus: '6.00'
          memory: 10G
    env_file:
      - default.env
    volumes:
      - /docker/game/enshrouded:/home/steam/enshrouded/savegame
