---
services:
  docker-socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: docker-socket-proxy
    restart: unless-stopped
    environment:
      CONTAINERS: "1"
      INFO: "1"
      PING: "1"
      POST: "0"
      IMAGES: "0"
      NETWORKS: "0"
      VOLUMES: "0"
      EXEC: "0"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "192.168.1.216:2375:2375"
