---
services:
  minecraft-valhelsia:
    image: itzg/minecraft-server:java17
    container_name: mcatm10
    hostname: mcatm10
    restart: unless-stopped
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
      - 8100:8100
      - 8123:8123
    volumes:
      - /docker/game/minecraft/minecraft_data:/data
      - ./allowed_users.json:/data/allowed_users.json
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '8'
          memory: 16G
