server {
    listen 80;
    server_name logs.rt-541.io;
    root /usr/share/nginx/html;
    index index.html;
    location /ws {
        proxy_pass http://goaccess:7890;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 7d;
    }
    location / { try_files $uri $uri/ /index.html; }
}
